/**
 * Report Sharing Engine for NSVAIR Diagnosis
 * Formats and dispatches medical reports to WhatsApp and Gmail / Email.
 * Default Phone: +91 9599497690
 * Default Email: nsvairdiagnosis@gmail.com
 */

import type { DiagnosisResult, UserProfile, ComprehensiveReport } from '@/lib/types'

export const DEFAULT_WHATSAPP_NUMBER = '919599497690' // 9599497690 with country code
export const DEFAULT_GMAIL_ADDRESS = 'nsvairdiagnosis@gmail.com'

/**
 * Clean phone number into international WhatsApp format (defaults to India +91 if 10 digits)
 */
export function cleanPhoneNumber(phone: string): string {
  const cleaned = phone.replace(/[^0-9]/g, '')
  if (cleaned.length === 10) {
    return `91${cleaned}`
  }
  return cleaned || DEFAULT_WHATSAPP_NUMBER
}

/**
 * Format a Comprehensive Multi-Module Diagnostic Report for WhatsApp
 */
export function formatComprehensiveReportWhatsAppMessage(
  report: {
    overallSummary: string
    overallRiskScore: number
    topFindings: DiagnosisResult['findings']
    prioritizedRecommendations: string[]
    redFlags: string[]
    nextSteps: string[]
    createdAt?: string
  },
  results: DiagnosisResult[],
  userProfile?: UserProfile
): string {
  const dateStr = new Date(report.createdAt || Date.now()).toLocaleDateString('en-US', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
  const patientName = userProfile?.name?.trim() || 'Anonymous Patient'
  const patientAge = userProfile?.age ? `${userProfile.age} yrs` : 'N/A'
  const patientGender = userProfile?.gender ? userProfile.gender.toUpperCase() : 'N/A'
  const patientBlood = userProfile?.bloodGroup || 'N/A'
  const patientBmi = userProfile?.bmi ? `${userProfile.bmi} (${userProfile.bmiCategory || 'Normal'})` : 'N/A'

  const riskStatus =
    report.overallRiskScore > 75
      ? '🔴 CRITICAL RISK'
      : report.overallRiskScore > 50
      ? '🟠 HIGH RISK'
      : report.overallRiskScore > 25
      ? '🟡 MODERATE RISK'
      : '🟢 LOW RISK'

  let msg = `🏥 *NSVAIR DIAGNOSIS — CLINICAL HEALTH REPORT*\n`
  msg += `*Powered by NSVAIR GROUP OF INDUSTRY*\n`
  msg += `──────────────────────────────\n`
  msg += `📋 *Report ID:* NSV-COMP-${Date.now().toString().slice(-6)}\n`
  msg += `📅 *Date:* ${dateStr}\n`
  msg += `👤 *Patient:* ${patientName} (${patientAge}, ${patientGender})\n`
  msg += `🩸 *Blood Group / BMI:* ${patientBlood} • BMI ${patientBmi}\n`
  msg += `📊 *Unified Risk Score:* ${report.overallRiskScore}/100 (${riskStatus})\n\n`

  msg += `📝 *EXECUTIVE SUMMARY:*\n${report.overallSummary}\n\n`

  if (report.redFlags && report.redFlags.length > 0) {
    msg += `⚠️ *CLINICAL RED FLAGS:*\n`
    report.redFlags.forEach((rf) => {
      msg += `• 🚨 ${rf}\n`
    })
    msg += `\n`
  }

  if (results && results.length > 0) {
    msg += `🔬 *COMPLETED DIAGNOSTIC TESTS (${results.length}):*\n`
    results.forEach((r, idx) => {
      msg += `${idx + 1}. *${r.moduleName}* (Risk: ${r.riskScore}/100 - ${r.riskLevel.toUpperCase()})\n`
      if (r.findings && r.findings[0]) {
        msg += `   ↳ Finding: ${r.findings[0].condition} (${Math.round(r.findings[0].confidence * 100)}% conf.)\n`
      }
    })
    msg += `\n`
  }

  if (report.prioritizedRecommendations && report.prioritizedRecommendations.length > 0) {
    msg += `💡 *KEY RECOMMENDATIONS:*\n`
    report.prioritizedRecommendations.slice(0, 4).forEach((rec, idx) => {
      msg += `${idx + 1}. ${rec}\n`
    })
    msg += `\n`
  }

  msg += `──────────────────────────────\n`
  msg += `⚠️ *Medical Disclaimer:* This report is generated by NSVAIR Diagnosis for screening and informational purposes. Please review with a certified physician.\n`
  msg += `🌐 *Platform:* https://nsvair-diagnosis.onrender.com\n`
  msg += `📧 *Official Contact:* nsvairdiagnosis@gmail.com`

  return msg
}

/**
 * Format a Single-Test Diagnostic Report for WhatsApp
 */
export function formatSingleTestWhatsAppMessage(
  result: DiagnosisResult,
  userProfile?: UserProfile
): string {
  const dateStr = new Date(result.completedAt || Date.now()).toLocaleDateString('en-US', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
  const patientName = userProfile?.name?.trim() || 'Anonymous Patient'
  const patientAge = userProfile?.age ? `${userProfile.age} yrs` : 'N/A'
  const patientGender = userProfile?.gender ? userProfile.gender.toUpperCase() : 'N/A'

  let msg = `🏥 *NSVAIR DIAGNOSIS — ${result.moduleName.toUpperCase()} REPORT*\n`
  msg += `*Powered by NSVAIR GROUP OF INDUSTRY*\n`
  msg += `──────────────────────────────\n`
  msg += `📅 *Date:* ${dateStr}\n`
  msg += `👤 *Patient:* ${patientName} (${patientAge}, ${patientGender})\n`
  msg += `📊 *Test Score:* ${result.riskScore}/100 (${result.riskLevel.toUpperCase()} RISK)\n\n`

  msg += `📝 *FINDINGS & ANALYSIS:*\n${result.summary}\n\n`

  if (result.findings && result.findings.length > 0) {
    msg += `🔍 *OBSERVATIONS:*\n`
    result.findings.forEach((f, idx) => {
      msg += `• *${f.condition}* [${f.severity.toUpperCase()}] (${Math.round(f.confidence * 100)}% conf.)\n`
      msg += `  ${f.description}\n`
      msg += `  ↳ Action: ${f.recommendation}\n`
    })
    msg += `\n`
  }

  if (result.recommendations && result.recommendations.length > 0) {
    msg += `💡 *RECOMMENDATIONS:*\n`
    result.recommendations.slice(0, 3).forEach((r, idx) => {
      msg += `${idx + 1}. ${r}\n`
    })
    msg += `\n`
  }

  msg += `──────────────────────────────\n`
  msg += `🌐 *NSVAIR Diagnosis* • Contact: nsvairdiagnosis@gmail.com`

  return msg
}

/**
 * Format a Comprehensive Diagnostic Report for Gmail / Email
 */
export function formatComprehensiveReportEmail(
  report: {
    overallSummary: string
    overallRiskScore: number
    topFindings: DiagnosisResult['findings']
    prioritizedRecommendations: string[]
    redFlags: string[]
    nextSteps: string[]
    createdAt?: string
  },
  results: DiagnosisResult[],
  userProfile?: UserProfile
): { subject: string; body: string } {
  const patientName = userProfile?.name?.trim() || 'Patient'
  const dateStr = new Date(report.createdAt || Date.now()).toLocaleDateString('en-US', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  })

  const subject = `[Medical Report] NSVAIR Diagnosis Health Assessment — ${patientName} (${dateStr})`

  const body = `NSVAIR DIAGNOSIS — COMPREHENSIVE HEALTH REPORT
Powered by NSVAIR GROUP OF INDUSTRY
Official Portal: https://nsvair-diagnosis.onrender.com
Contact: nsvairdiagnosis@gmail.com
================================================================================

PATIENT DETAILS:
• Name: ${patientName}
• Age / Gender: ${userProfile?.age || 'N/A'} yrs / ${userProfile?.gender || 'N/A'}
• Blood Group: ${userProfile?.bloodGroup || 'N/A'}
• BMI: ${userProfile?.bmi || 'N/A'} (${userProfile?.bmiCategory || 'Normal'})
• Pre-existing Conditions: ${userProfile?.conditions || 'None reported'}
• Known Allergies: ${userProfile?.allergies || 'None reported'}
• Report Date: ${new Date(report.createdAt || Date.now()).toLocaleString()}

--------------------------------------------------------------------------------
UNIFIED RISK ASSESSMENT:
Risk Score: ${report.overallRiskScore}/100 (${report.overallRiskScore > 50 ? 'HIGH' : report.overallRiskScore > 25 ? 'MODERATE' : 'LOW'} RISK)

EXECUTIVE SUMMARY:
${report.overallSummary}

${
  report.redFlags && report.redFlags.length > 0
    ? `\nCLINICAL RED FLAGS:\n${report.redFlags.map((f) => `• [ALERT] ${f}`).join('\n')}\n`
    : ''
}
--------------------------------------------------------------------------------
COMPLETED DIAGNOSTIC BATTERY (${results.length} MODULES):
${results
  .map(
    (r, idx) =>
      `${idx + 1}. ${r.moduleName} (Score: ${r.riskScore}/100, ${r.riskLevel.toUpperCase()})\n   Summary: ${r.summary}\n   ${
        r.findings?.[0]
          ? `Primary Finding: ${r.findings[0].condition} (${Math.round(r.findings[0].confidence * 100)}% conf.)`
          : ''
      }`
  )
  .join('\n\n')}

--------------------------------------------------------------------------------
PRIORITIZED RECOMMENDATIONS:
${(report.prioritizedRecommendations || []).map((r, i) => `${i + 1}. ${r}`).join('\n')}

RECOMMENDED NEXT STEPS:
${(report.nextSteps || []).map((s, i) => `${i + 1}. ${s}`).join('\n')}

================================================================================
DISCLAIMER:
This AI clinical screening document was synthesized by NSVAIR Diagnosis (Powered by NSVAIR GROUP OF INDUSTRY) for wellness and health awareness purposes. It is not an official primary medical diagnosis. Please consult a qualified licensed physician for medical advice and treatment.
`

  return { subject, body }
}

/**
 * Dispatch message directly to WhatsApp Web / App
 */
export function openWhatsApp(phone: string, message: string) {
  const targetPhone = cleanPhoneNumber(phone)
  const encoded = encodeURIComponent(message)
  const url = `https://wa.me/${targetPhone}?text=${encoded}`
  window.open(url, '_blank')
}

/**
 * Dispatch email via Gmail Web or Default Email Client (mailto:)
 */
export function openEmail(
  email: string,
  subject: string,
  body: string,
  preferGmailWeb: boolean = true
) {
  const targetEmail = email.trim() || DEFAULT_GMAIL_ADDRESS
  const encSubject = encodeURIComponent(subject)
  const encBody = encodeURIComponent(body)

  if (preferGmailWeb) {
    // Open Gmail compose window directly in browser
    const gmailUrl = `https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(targetEmail)}&su=${encSubject}&body=${encBody}`
    window.open(gmailUrl, '_blank')
  } else {
    // Fallback to mailto client
    window.location.href = `mailto:${targetEmail}?subject=${encSubject}&body=${encBody}`
  }
}
